import { useEffect, useState } from "react";
import { Printer } from "lucide-react";
import { api } from "../../services/api";
import { Button, dateFmt, money } from "../../components/UI";
export default function Receipts() {
  const [items, setItems] = useState([]);
  useEffect(() => {
    api.get("/payments/receipts").then((r) => setItems(r.data.data));
  }, []);
  return (
    <>
      <div className="page-head">
        <div className="page-title">
          <h1>Receipts</h1>
          <p>Verified payment receipts generated by RC ERP.</p>
        </div>
      </div>
      <div className="panel">
        <div className="table-wrap">
          <table className="data-table">
            <thead>
              <tr>
                <th>Receipt No.</th>
                <th>Vendor</th>
                <th>Amount</th>
                <th>Payment Mode</th>
                <th>Transaction ID</th>
                <th>Generated By</th>
                <th>Date</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {items.map((r) => (
                <tr key={r._id}>
                  <td>
                    <strong>{r.receiptNo}</strong>
                  </td>
                  <td>{r.vendor?.vendorName}</td>
                  <td>{money(r.amount)}</td>
                  <td>{r.paymentMode}</td>
                  <td>{r.transactionId}</td>
                  <td>{r.generatedBy?.fullName}</td>
                  <td>{dateFmt(r.createdAt)}</td>
                  <td>
                    <Button
                      kind="secondary"
                      icon={Printer}
                      onClick={() => window.print()}
                    >
                      Print
                    </Button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </>
  );
}
