import { useEffect, useState } from "react";
import { Printer } from "lucide-react";
import { api } from "../../services/api";
import { Button, dateFmt, money } from "../../components/UI";
import * as tw from "../../styles/tw";

export default function Receipts() {
  const [items, setItems] = useState([]);
  useEffect(() => {
    api.get("/payments/receipts").then((r) => setItems(r.data.data));
  }, []);
  return (
    <>
      <div className={tw.pageHead}>
        <div>
          <h1 className={tw.pageTitleH1}>Receipts</h1>
          <p className={tw.pageTitleP}>Verified payment receipts generated by RC ERP.</p>
        </div>
      </div>
      <div className={tw.panel}>
        <div className={tw.tableWrap}>
          <table className={tw.dataTable}>
            <thead>
              <tr>
                <th className={tw.th}>Receipt No.</th>
                <th className={tw.th}>Vendor</th>
                <th className={tw.th}>Amount</th>
                <th className={tw.th}>Payment Mode</th>
                <th className={tw.th}>Transaction ID</th>
                <th className={tw.th}>Generated By</th>
                <th className={tw.th}>Date</th>
                <th className={tw.th}>Action</th>
              </tr>
            </thead>
            <tbody>
              {items.map((r) => (
                <tr key={r._id} className={tw.tr}>
                  <td className={tw.td}>
                    <strong className={tw.tdStrong}>{r.receiptNo}</strong>
                  </td>
                  <td className={tw.td}>{r.vendor?.vendorName}</td>
                  <td className={tw.td}>{money(r.amount)}</td>
                  <td className={tw.td}>{r.paymentMode}</td>
                  <td className={tw.td}>{r.transactionId}</td>
                  <td className={tw.td}>{r.generatedBy?.fullName}</td>
                  <td className={tw.td}>{dateFmt(r.createdAt)}</td>
                  <td className={tw.td}>
                    <Button
                      kind="secondary"
                      icon={Printer}
                      onClick={() => window.print()}
                    >
                      Print
                    </Button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </>
  );
}
